# Generated by Django 3.2.5 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Прозвище юзера')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('status_email', models.BooleanField(default=False, verbose_name='Подтверждён email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка')),
                ('company', models.BooleanField(default=False, verbose_name='Компания или нет')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='user', to='courses.Course', verbose_name='Курсы в которые записан')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
    ]
