# Generated by Django 3.2.5 on 2021-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_test_section'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracademy',
            name='complete_tests',
            field=models.ManyToManyField(related_name='user', to='lessons.Test', verbose_name='Выполненные тесты'),
        ),
    ]
