# Generated by Django 3.2.9 on 2022-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20220206_1726'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademy',
            name='complete_tests',
            field=models.ManyToManyField(blank=True, related_name='user', to='lessons.ContentUnit', verbose_name='Выполненные тесты'),
        ),
    ]
