# Generated by Django 3.2.5 on 2021-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_useracademy_complete_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracademy',
            name='balls',
            field=models.IntegerField(default=0, verbose_name='Количество баллов за все курсы'),
        ),
    ]
