# Generated by Django 3.2.5 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('school_predmet', models.BooleanField(default=False, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=1200)),
                ('description', models.TextField(max_length=3500)),
                ('community', models.TextField(max_length=900, verbose_name='На кого расчитан курс')),
                ('requirements', models.TextField(max_length=900, verbose_name='Требования')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский'), ('Немецкий', 'Немецкий'), ('Французский', 'Французкий'), ('Испанский', 'Испанский')], max_length=200, null=True, verbose_name='Язык')),
                ('image', models.ImageField(upload_to='')),
                ('status_money', models.BooleanField(default=False, verbose_name='Платный')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена курса')),
                ('status_certificate', models.BooleanField(default=False, verbose_name='Сертификат')),
                ('travel_time', models.PositiveIntegerField(default=1, verbose_name='Примерное время прохождения')),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
