# Generated by Django 3.2.5 on 2021-08-28 13:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое теста')),
                ('right_answer', models.CharField(max_length=400, verbose_name='Правильный ответ')),
                ('variant_1', models.CharField(max_length=400, verbose_name='Вариант 1')),
                ('variant_2', models.CharField(max_length=400, verbose_name='Вариант 2')),
                ('variant_3', models.CharField(max_length=400, verbose_name='Вариант 3')),
                ('variant_4', models.CharField(blank=True, max_length=400, null=True, verbose_name='Вариант 4')),
                ('variant_5', models.CharField(blank=True, max_length=400, null=True, verbose_name='Вариант 5')),
                ('variant_6', models.CharField(blank=True, max_length=400, null=True, verbose_name='Вариант 6')),
                ('variant_7', models.CharField(blank=True, max_length=400, null=True, verbose_name='Вариант 7')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TopicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='SectionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Секция темы')),
                ('balls', models.IntegerField(default=1, verbose_name='Количество баллов за урок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.topiccourse', verbose_name='Тема курса')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название урока')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент урока')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.sectiontopic', verbose_name='Секция уроков')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
