# Generated by Django 3.2.9 on 2022-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentunit',
            name='step_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер степа'),
        ),
    ]
