# Generated by Django 3.2.5 on 2021-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectiontopic',
            options={'verbose_name': 'Cекция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='topiccourse',
            options={'verbose_name': 'Тема курса', 'verbose_name_plural': 'Темы курса'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Контент урока'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(verbose_name='Содержимое теста'),
        ),
    ]
