# Generated by Django 3.2.5 on 2021-08-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210829_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.sectiontopic', verbose_name='секция'),
            preserve_default=False,
        ),
    ]
