# Generated by Django 3.2.5 on 2021-09-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_test_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lessons.topiccourse', verbose_name='Тема курса'),
        ),
    ]
