# Generated by Django 3.2.5 on 2021-09-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_sectiontopic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.sectiontopic', verbose_name='Секция уроков'),
        ),
    ]
