# Generated by Django 3.2.5 on 2021-09-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('lessons', '0005_alter_lesson_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course', verbose_name='Курс'),
        ),
    ]
