# Generated by Django 3.2.5 on 2021-09-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_topiccourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lessons.sectiontopic', verbose_name='секция'),
        ),
    ]
