# Generated by Django 3.2.5 on 2021-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_test_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontopic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
